---

- name: apply selinux fcontext
  ansible.builtin.command: restorecon -irv {{ nextcloud_root_path }}
  when: selinux_configuration.changed
  become: true

- name: restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes
    state: restarted
  when: ntp_configuration.changed
  become: true

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted
  when: nginx_configuration.changed
  become: true

- name: restart php-fpm
  ansible.builtin.systemd:
    name: php-fpm
    enabled: yes
    state: restarted
  when: phpfpm_configuration.changed
  become: true
