---

- name: open port 80/service http
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  become: true

- name: open port 443/service https
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
  become: true
