---

- name: installing needed packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  become: true

- name: installing psycopg2 for postgresql task
  ansible.builtin.pip:
    name: psycopg2-binary
  become: true

- name: download nextcloud and unzip
  ansible.builtin.unarchive:
    src: https://download.nextcloud.com/server/releases/latest.zip
    dest: "{{ temp_path }}"
    remote_src: yes
  args:
    creates: "{{ temp_path }}nextcloud/"

- name: copy downloaded version to the right path with the correct permissions
  ansible.builtin.copy:
    src: "{{ temp_path }}/nextcloud/"
    dest: "{{ nextcloud_root_path }}"
    remote_src: yes
    force: no
    owner: nginx
    group: nginx
    mode: '0755'
  become: true
