---

- name: Copy domain config to remote-host
  ansible.builtin.template:
    src: templates/nginx/domain.conf.j2
    dest: /etc/nginx/conf.d/{{ config_file_name }}.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  register: nginx_configuration
  notify:
    - restart nginx

- name: Copy nginx config to remote-host
  ansible.builtin.template:
    src: templates/nginx/nginx_main_configuration.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  register: nginx_configuration
  notify:
    - restart nginx

- name: Copy agent block rules for nginx
  ansible.builtin.template:
    src: templates/nginx/agents.rules.j2
    dest: /etc/nginx/agents.rules
    owner: root
    group: root
    mode: '0644'
  become: true
  register: nginx_configuration
  notify:
    - restart nginx

- name: Start and enable nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: restarted
  become: true
