---

- name: installing needed packages
  dnf:
    name: "{{ packages }}" 
    state: present
  become: yes

- name: installing psycopg2 for the dbscript
  pip:
    name: psycopg2-binary
  
- name: download nextcloud and unzip
  ansible.builtin.unarchive:
    src: https://download.nextcloud.com/server/releases/nextcloud-23.0.2.zip
    dest: "{{ temp_path }}"
    remote_src: yes

- name: copy downloaded version to the right path with the right permissions
  ansible.builtin.copy:
    src: "{{ temp_path }}/nextcloud/"
    dest: "{{ target_path }}"
    remote_src: yes
    owner: nginx
    group: nginx
    mode: '0755'
  become: yes
