---

- name: Add nginx to redis group
  ansible.builtin.user:
    name: nginx
    groups: redis
    append: true
    state: present
  become: true

- name: Copy config file to remote-host
  ansible.builtin.template:
    src: templates/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: root
    mode: '0640'
  become: true

- name: Start redis service
  ansible.builtin.systemd:
    name: redis
    enabled: true
    state: restarted
  become: true
