---

- name: add nginx to redis group
  ansible.builtin.shell: usermod -aG redis nginx
  become: true

- name: add nginx to /etc/group => redis:xxx:nginx
  ansible.builtin.lineinfile:
    path: /etc/group
    regexp: '^redis:x:990:'
    line: redis:x:990:nginx
    owner: root
    group: root
    mode: '0644'
  become: true

- name: copy config file to remote-host
  ansible.builtin.template:
    src: templates/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: root
    mode: '0640'
  become: true

- name: start redis service
  ansible.builtin.systemd:
    name: redis
    enabled: true
    state: restarted
  become: true
