---

- name: copy domain config to remote-host
  ansible.builtin.template:
    src: templates/nginx/domain.conf.j2
    dest: /etc/nginx/conf.d/nextcloud.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: copy nginx config to remote-host
  ansible.builtin.template:
    src: templates/nginx/nginx_standard.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: copy agent block rules for nginx
  ansible.builtin.template:
    src: templates/nginx/agents.rules.j2
    dest: /etc/nginx/agents.rules
    owner: root
    group: root
    mode: '0644'
  become: yes
  register: nginx_configuration
  notify:
    - restart nginx
