---

- name: set RW permissions for nginx and php-fpm
  community.general.sefcontext:
    target: '{{ nextcloud_root_path }}(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  become: true
  register: selinux_configuration
  notify:
    - apply selinux fcontext

- name: allow php-fpm to use execmem
  ansible.posix.seboolean:
    name: httpd_execmem
    state: true
    persistent: true
  become: true

- name: set permissions for the system to make network requests
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  become: true

- name: change group owner of content in /var/lib/php/ to nginx instead of apache 1/3
  ansible.posix.acl:
    path: /var/lib/php/opcache/
    entity: nginx
    etype: user
    permissions: rwx
    state: present
  become: true

- name: change group owner of content in /var/lib/php/ to nginx instead of apache 2/3
  ansible.posix.acl:
    path: /var/lib/php/session/
    entity: nginx
    etype: user
    permissions: rwx
    state: present
  become: true

- name: change group owner of content in /var/lib/php/ to nginx instead of apache 3/3
  ansible.posix.acl:
    path: /var/lib/php/wsdlcache/
    entity: nginx
    etype: user
    permissions: rwx
    state: present
  become: true
