---
# main task file for NXTC-ROLE

- name: import tasks
  include_tasks: "{{ item }}"
  loop:
    - 01_setup_hostnames.yml
    - 02_configure_firewall.yml
    - 03_setup_ntp.yml
    - 04_installing_packages.yml
    - 05_configure_nginx.yml
    - 06_configure_php.yml
    - 07_configure_postgresql.yml
    - 08_set_permissions_for_acl_and_selinux.yml

